### ISSUE TITLE
Codeium in vscode on .ipynb files

### ISSUE THREAD

**Issue by mgazzin** [Exafunction/codeium#110]
Hello, I use Codeium for my personal code.
I have vscode with Codeium and I can easily use Codeium on .py file but it does not work on .ipynb files.
I did not find any documentation on setting up Codeium for Jupyter notebooks in vscode.
Can anyone help me?

**Comment by A-k-a-sh** [comment]
Follow this - https://codeium.com/jupyter_tutorial

**Comment by mgazzin** [comment]
ok it works. thanks.
