### ISSUE TITLE
Feature Request - Extension for Kate (KDE)

### ISSUE THREAD

**Issue by special-k-anon** [Exafunction/codeium#16]
Kate is a powerful editor by KDE, very similar to VS Code. Even though it lacks some of my favorite extensions, Kate's performance is so good that I prefer it over anything else. There's actually no AI extensions available yet for Kate so I'd love to see a Codeium extension.

https://github.com/KDE/kate
https://kate-editor.org/

Thanks!

**Comment by pqn** [comment]
Unfortunately we don't have the bandwidth to work on a first party Kate extension right now, but there are enough open source implementations of our API (notably https://github.com/Exafunction/codeium-chrome and https://github.com/Exafunction/codeium.vim) that someone in the community could take it on.
