### ISSUE TITLE
Error on VS Code : `Client codeium: connection to server is erroring. Shutting down server.`

### ISSUE THREAD

**Issue by zb81** [Exafunction/codeium#24]
### Output Error

```
[Error - 09:50:31] Client codeium: connection to server is erroring. Shutting down server.
[Error - 09:50:31] Client codeium: connection to server is erroring. Shutting down server.
[Error - 09:50:31] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2518208)
	at b.stop (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2517789)
	at b.stop (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2680077)
	at b.handleConnectionError (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2524296)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 09:50:31] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at b.shutdown (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2518208)
	at b.stop (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2517789)
	at b.stop (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2680077)
	at b.handleConnectionError (/Users/zb/.vscode/extensions/codeium.codeium-1.6.10/dist/extension.js:2:2524296)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 09:50:31] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 09:50:31] Connection to server got closed. Server will restart.
true
[Error - 09:50:31] codeium client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 09:50:31] codeium client: couldn't create connection to server.
Error: connect ECONNREFUSED 127.0.0.1:52516
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
[Error - 09:50:31] Restarting server failed
Error: connect ECONNREFUSED 127.0.0.1:52516
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

### VS Code version

```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
```

**Comment by ShawSpring** [comment]
I‘m facing the same issue.  It takes so long to Downloading Codeium language server when install the codeium extension, then the Error output appeared.

**Comment by maooyer** [comment]
Same issue. It looks like a language server bug. In my case, the language server log shows LSP listening on port 52112，but I cannot found server listening on listening the port

**vscode log**
```
[Info  - 00:19:17] Connection to server got closed. Server will restart.
true
[Error - 00:19:17] codeium client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 00:19:17] codeium client: couldn't create connection to server.
Error: connect ECONNREFUSED 127.0.0.1:52112
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
[Error - 00:19:17] Restarting server failed
Error: connect ECONNREFUSED 127.0.0.1:52112
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

**server log**
``` 
I1215 00:19:17.454112 11004 server.go:341] Language server will attempt to listen on host 127.0.0.1
I1215 00:19:17.454306 11004 server.go:385] Language server listening on random port at 52111
I1215 00:19:17.454313 11004 server.go:387] LSP listening on random port at 52112
I1215 00:19:17.454867 11004 web_server.go:229] Chat Web Server listening at ws://127.0.0.1:52113
I1215 00:19:17.650026 11004 server.go:1741] Skipped changelog download for version 1.6.10
```

<img width="1009" alt="image" src="https://github.com/Exafunction/codeium/assets/1215295/8c4eff30-f2e9-474c-b692-507a300f0b96">

**Comment by pqn** [comment]
Upgrade to 1.6.11 and it should be fixed.

**Comment by pqn** [comment]
Oops, it appears this release failed, we're retrying it now.

**Comment by pqn** [comment]
Should be updated now.

**Comment by blueseye** [comment]
I used 1.16.3, but I had the same problem.
![image](https://github.com/user-attachments/assets/c1232dae-80f2-46c4-abb1-b66922413c1f)
I0919 23:49:51.075237 34484 server.go:255] LSP listening on random port at 61604
I0919 23:49:51.078035 34484 web_server.go:250] Chat Web Server listening at ws://127.0.0.1:61606
I0919 23:49:51.096731  7928 main.go:295] LS MANAGER: Language server manager found random server port 61599
I0919 23:49:51.096731  7928 main.go:296] LS MANAGER: Language server manager found random lsp port 61604
I0919 23:49:51.096731  7928 main.go:303] LS MANAGER: Language server manager attempting to connect to language server at 127.0.0.1:61599
I0919 23:49:51.121128  7928 main.go:174] LS MANAGER: Fixing language server port at 61599
I0919 23:49:51.121128  7928 main.go:354] LS MANAGER: Language server manager successfully connected to new language server at 127.0.0.1:61599
61604
(VSCode) 2024-09-19 23:49:51.424 [INFO]: Found language server running on port 61599
I0919 23:49:51.444525 34484 utils.go:228] Analyzing workspace files for c:/workplace
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x78 pc=0xd48777]

goroutine 167 [running]:
github.com/Exafunction/Exafunction/exa/fs.PathFromUriString({0xc003289960?, 0xc002c93488?})
	exa/fs/uri.go:118 +0x57
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.SafeFilename({{0xc003289960?, 0xc001fb85a0?}})
	exa/fs/workspace_manager/utils.go:62 +0x34
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.shouldIgnorePath({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb6d20?, 0x0?}}, {0xc002cb1500, 0x2, 0x0?})
	exa/fs/workspace_manager/utils.go:180 +0x232
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.IsTrackedPath(...)
	exa/fs/workspace_manager/utils.go:200
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.ComputeWorkspaceFiles.func1({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb6d20?, 0x4f6cfc78?}}, {0x4611c08, 0xc00131d880}, {0x0?, 0x0?})
	exa/fs/workspace_manager/utils.go:252 +0x2a5
github.com/Exafunction/Exafunction/exa/fs.Path.WalkDir.func1({0xc002cb6d20?, 0x0?}, {0x4611c08?, 0xc00131d880?}, {0x0?, 0x0?})
	exa/fs/path.go:239 +0x5e
io/fs.walkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb6d20, 0x14}, {0x4611c08, 0xc00131d880}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb69cb, 0x9}, {0x4611c40, 0xc001fb9370}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:95 +0x2bf
io/fs.WalkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb69cb, 0x9}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:122 +0xa5
github.com/hack-pad/hackpadfs.WalkDir(...)
	external/com_github_hack_pad_hackpadfs/fs.go:136
github.com/Exafunction/Exafunction/exa/fs.Path.WalkDir({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb69cb?, 0x3806348?}}, 0x9880648?)
	exa/fs/path.go:247 +0x92
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.ComputeWorkspaceFiles({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb69cb?, 0x14?}}, {0xc002cb1500, 0x2, 0x2}, 0x0)
	exa/fs/workspace_manager/utils.go:232 +0x285
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.(*WorkspaceInfoManager).AddWorkspaceFolder(0xc00199b200, {{0xc002cb69c0?, 0xc00052ada4?}})
	exa/fs/workspace_manager/workspace_manager.go:206 +0x699
github.com/Exafunction/Exafunction/exa/language_server/lsp.(*LspClient).AddWorkspaceFolder(0x34c8c80?, {0xc002cb69a8, 0x16})
	exa/language_server/lsp/lsp.go:91 +0xa4
github.com/Exafunction/Exafunction/exa/language_server/lsp.(*LspClient).Initialize(0xc0025925c0, {0x2f76740?, 0xc0018e6b00?}, 0xffffffffffffffff?)
	exa/language_server/lsp/lsp.go:116 +0x6a
go.lsp.dev/protocol.serverDispatch({0x4611a80, 0xc002682000}, {0x46b9030, 0xc0025925c0}, 0xc0032968e0, {0x509f3e40, 0xc0032a2880})
	external/dev_lsp_go_protocol/server.go:76 +0x1036
github.com/Exafunction/Exafunction/exa/language_server/lsp.Serve.ServerHandler.func2({0x4611a80, 0xc002682000}, 0xc0032968e0, {0x509f3e40, 0xc0032a2880})
	external/dev_lsp_go_protocol/server.go:36 +0x7e
go.lsp.dev/jsonrpc2.(*conn).run(0xc002a33270, {0x4611a80, 0xc002682000}, 0xc002184000)
	external/dev_lsp_go_jsonrpc2/conn.go:206 +0x33f
created by go.lsp.dev/jsonrpc2.(*conn).Go in goroutine 122
	external/dev_lsp_go_jsonrpc2/conn.go:189 +0x8f
(VSCode) 2024-09-19 23:49:51.586 [ERROR]: [unavailable] connect ECONNREFUSED 127.0.0.1:61599
(VSCode) 2024-09-19 23:49:51.865 [ERROR]: [unavailable] connect ECONNREFUSED 127.0.0.1:61599
