### ISSUE TITLE
Completion 28 error: deadline_exceeded

### ISSUE THREAD

**Issue by soltanireza65** [Exafunction/codeium#25]
2023-12-16 11:12:02.804 [INFO]: Completion request was cancelled by token (69.09ms)
2023-12-16 11:12:07.961 [INFO]: [Language Server (stderr)]:
E1216 11:12:07.961099  3335 api_server_client.go:340] Completion 28 error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetCompletions": context deadline exceeded
2023-12-16 11:12:07.964 [ERROR]: [deadline_exceeded] Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetCompletions": context deadline exceeded
2023-12-16 11:12:07.964 [INFO]: Completion request errored (5083.42ms)
2023-12-16 11:12:07.964 [ERROR]: [deadline_exceeded] Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetCompletions": context deadline exceeded
2023-12-16 11:12:21.096 [INFO]: [Language Server (stderr)]:
E1216 11:12:21.095098  3335 api_server_client.go:1231] GetUserStatus error: deadline_exceeded: Post "https://server.codeium.com/exa.seat_management_pb.SeatManagementService/GetUserStatus": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:12:21.098 [ERROR]: [deadline_exceeded] Post "https://server.codeium.com/exa.seat_management_pb.SeatManagementService/GetUserStatus": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:12:21.526 [INFO]: [Language Server (stderr)]:
E1216 11:12:21.526296  3335 api_server_client.go:685] RecordEvent error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/RecordEvent": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:12:33.218 [INFO]: [Language Server (stderr)]:
E1216 11:12:33.216821  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
E1216 11:12:33.216821  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
E1216 11:12:33.216821  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:12:50.849 [INFO]: [Language Server (stderr)]:
E1216 11:12:50.848850  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": dial tcp 35.223.238.178:443: i/o timeout (Client.Timeout exceeded while awaiting headers)

E1216 11:12:50.848925  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:13:50.851 [INFO]: [Language Server (stderr)]:
E1216 11:13:50.850352  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:13:50.850452  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:14:50.851 [INFO]: [Language Server (stderr)]:
E1216 11:14:50.850642  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:14:50.850729  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:15:50.855 [INFO]: [Language Server (stderr)]:
E1216 11:15:50.854510  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:15:50.855 [INFO]: [Language Server (stderr)]:
E1216 11:15:50.854724  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:16:50.856 [INFO]: [Language Server (stderr)]:
E1216 11:16:50.856253  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:16:50.856277  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": dial tcp 35.223.238.178:443: i/o timeout (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:17:21.401 [INFO]: [Language Server (stderr)]:
E1216 11:17:21.400713  3335 api_server_client.go:665] Error traces error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/RecordAsyncTelemetry": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:17:50.857 [INFO]: [Language Server (stderr)]:
E1216 11:17:50.856658  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:17:50.856735  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:18:08.787 [INFO]: [Language Server (stderr)]:
E1216 11:18:08.785056  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
E1216 11:18:08.785070  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
E1216 11:18:08.785123  3335 api_server_client.go:597] GetEmbeddings error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/GetEmbeddings": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:18:50.868 [INFO]: [Language Server (stderr)]:
E1216 11:18:50.868106  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:18:50.868129  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:19:50.880 [INFO]: [Language Server (stderr)]:
E1216 11:19:50.879590  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:19:50.879646  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:20:50.879 [INFO]: [Language Server (stderr)]:
E1216 11:20:50.879182  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:20:50.879228  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:21:50.886 [INFO]: [Language Server (stderr)]:
E1216 11:21:50.883695  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:21:50.883840  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:22:21.101 [INFO]: [Language Server (stderr)]:
E1216 11:22:21.100154  3335 api_server_client.go:665] Error traces error: deadline_exceeded: Post "https://server.codeium.com/exa.api_server_pb.ApiServerService/RecordAsyncTelemetry": dial tcp 35.223.238.178:443: i/o timeout
2023-12-16 11:22:50.885 [INFO]: [Language Server (stderr)]:
E1216 11:22:50.883149  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:22:50.883277  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:23:50.887 [INFO]: [Language Server (stderr)]:
E1216 11:23:50.886348  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:23:50.887 [INFO]: [Language Server (stderr)]:
E1216 11:23:50.886803  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2023-12-16 11:24:50.886 [INFO]: [Language Server (stderr)]:
E1216 11:24:50.885417  3335 unleash.go:56] Unleash error: Post "https://unleash.codeium.com/api/client/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

E1216 11:24:50.885488  3335 unleash.go:56] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by anoduck** [comment]
I received a similar error in VS Code today, using both the release and the prerelease versions.

**Comment by fortenforge** [comment]
We're doing some maintenance. Please bear with us.

**Comment by anoduck** [comment]
@fortenforge The issue is no longer. Thanks.

**Comment by makarworld** [comment]
same problem in VS code now

```
2024-05-16 10:33:46.754 [INFO]: [Language Server (stderr)]:
I0516 10:33:46.754560  2288 rpcs_miscellaneous.go:312] University version is up to date.
2024-05-16 10:34:03.115 [INFO]: Completion request was cancelled by token (116.06ms)
2024-05-16 10:34:03.545 [INFO]: Completion request was cancelled by token (380.76ms)
2024-05-16 10:34:03.698 [INFO]: Completion request was cancelled by token (102.64ms)
2024-05-16 10:34:03.749 [INFO]: Skipping completions because autocomplete is open
2024-05-16 10:34:10.336 [INFO]: Completion request was cancelled by token (4942.69ms)
2024-05-16 10:34:15.488 [INFO]: [Language Server (stderr)]:
E0516 10:34:15.488406  2288 completion.go:298] Completion 57 error: deadline_exceeded: context deadline exceeded
2024-05-16 10:34:15.489 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:15.490 [INFO]: Completion request errored (5094.8ms)
2024-05-16 10:34:15.490 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:18.598 [INFO]: Completion request was cancelled by token (84.22ms)
2024-05-16 10:34:18.686 [INFO]: Completion request was cancelled by token (33.58ms)
2024-05-16 10:34:18.790 [INFO]: Completion request was cancelled by token (53.05ms)
2024-05-16 10:34:18.908 [INFO]: Completion request was cancelled by token (63.27ms)
2024-05-16 10:34:19.010 [INFO]: Completion request was cancelled by token (46.77ms)
2024-05-16 10:34:19.822 [INFO]: Completion request was cancelled by token (753.82ms)
2024-05-16 10:34:20.715 [INFO]: Completion request was cancelled by token (834.08ms)
2024-05-16 10:34:25.852 [INFO]: [Language Server (stderr)]:
E0516 10:34:25.852725  2288 completion.go:298] Completion 85 error: deadline_exceeded: context deadline exceeded
2024-05-16 10:34:25.854 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:25.854 [INFO]: Completion request errored (5089.55ms)
2024-05-16 10:34:25.854 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:34.220 [INFO]: [Language Server (stderr)]:
E0516 10:34:34.219732  2288 completion.go:298] Completion 103 error: deadline_exceeded: context deadline exceeded
2024-05-16 10:34:34.221 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:34.221 [INFO]: Completion request errored (5093.19ms)
2024-05-16 10:34:34.221 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:41.574 [INFO]: [Language Server (stderr)]:
E0516 10:34:41.574484  2288 completion.go:298] Completion 119 error: deadline_exceeded: context deadline exceeded
2024-05-16 10:34:41.575 [ERROR]: [deadline_exceeded] context deadline exceeded
2024-05-16 10:34:41.575 [INFO]: Completion request errored (5094.66ms)
2024-05-16 10:34:41.575 [ERROR]: [deadline_exceeded] context deadline exceeded
```

**Comment by Ahm3dRN** [comment]
> same problem in VS code now
> 
> ```
> 2024-05-16 10:33:46.754 [INFO]: [Language Server (stderr)]:
> I0516 10:33:46.754560  2288 rpcs_miscellaneous.go:312] University version is up to date.
> 2024-05-16 10:34:03.115 [INFO]: Completion request was cancelled by token (116.06ms)
> 2024-05-16 10:34:03.545 [INFO]: Completion request was cancelled by token (380.76ms)
> 2024-05-16 10:34:03.698 [INFO]: Completion request was cancelled by token (102.64ms)
> 2024-05-16 10:34:03.749 [INFO]: Skipping completions because autocomplete is open
> 2024-05-16 10:34:10.336 [INFO]: Completion request was cancelled by token (4942.69ms)
> 2024-05-16 10:34:15.488 [INFO]: [Language Server (stderr)]:
> E0516 10:34:15.488406  2288 completion.go:298] Completion 57 error: deadline_exceeded: context deadline exceeded
> 2024-05-16 10:34:15.489 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:15.490 [INFO]: Completion request errored (5094.8ms)
> 2024-05-16 10:34:15.490 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:18.598 [INFO]: Completion request was cancelled by token (84.22ms)
> 2024-05-16 10:34:18.686 [INFO]: Completion request was cancelled by token (33.58ms)
> 2024-05-16 10:34:18.790 [INFO]: Completion request was cancelled by token (53.05ms)
> 2024-05-16 10:34:18.908 [INFO]: Completion request was cancelled by token (63.27ms)
> 2024-05-16 10:34:19.010 [INFO]: Completion request was cancelled by token (46.77ms)
> 2024-05-16 10:34:19.822 [INFO]: Completion request was cancelled by token (753.82ms)
> 2024-05-16 10:34:20.715 [INFO]: Completion request was cancelled by token (834.08ms)
> 2024-05-16 10:34:25.852 [INFO]: [Language Server (stderr)]:
> E0516 10:34:25.852725  2288 completion.go:298] Completion 85 error: deadline_exceeded: context deadline exceeded
> 2024-05-16 10:34:25.854 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:25.854 [INFO]: Completion request errored (5089.55ms)
> 2024-05-16 10:34:25.854 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:34.220 [INFO]: [Language Server (stderr)]:
> E0516 10:34:34.219732  2288 completion.go:298] Completion 103 error: deadline_exceeded: context deadline exceeded
> 2024-05-16 10:34:34.221 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:34.221 [INFO]: Completion request errored (5093.19ms)
> 2024-05-16 10:34:34.221 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:41.574 [INFO]: [Language Server (stderr)]:
> E0516 10:34:41.574484  2288 completion.go:298] Completion 119 error: deadline_exceeded: context deadline exceeded
> 2024-05-16 10:34:41.575 [ERROR]: [deadline_exceeded] context deadline exceeded
> 2024-05-16 10:34:41.575 [INFO]: Completion request errored (5094.66ms)
> 2024-05-16 10:34:41.575 [ERROR]: [deadline_exceeded] context deadline exceeded
> ```

same

**Comment by anoduck** [comment]
@makarworld @Ahm3dRN As @fortenforge previously stated, this is only a temporary condition. When maintenance is completed on the server, life will be good once again.

**Comment by Battou2501** [comment]
Same issue! Today Codeium stopped working completely. Restarting VS Code or reinstalling extension does not help. Always "context deadline exceeded" error. IS it maintenance again? Is there a way of alerting users about them?

**Comment by RomanNemercev** [comment]
same mistake(

**Comment by javier-itg** [comment]
I am having the same issue since yesterday.

**Comment by atiberghien** [comment]
+1

**Comment by RomanNemercev** [comment]
> same mistake(

it's a live!

**Comment by LionelHolt** [comment]
Is it too late here to suggest notifications of Codeium downtime or at least an error message that indicates that better than "deadline_exceeded"? There have been other mysterious messages and seems like frequent downtime lately.

**Comment by RomanNemercev** [comment]
damn, it happened again(

**Comment by cethink** [comment]
Visual Studio v17.12.3
Codeium v1.8.93

```
Language Server: E1222 20:24:59.729001  7648 completion.go:215] Completion 0 from source PROVIDER_SOURCE_AUTOCOMPLETE error: context deadline exceeded
Language Server: E1222 20:24:59.729001  7648 completions_state_manager.go:833] Error streaming completions: context deadline exceeded
Error: Failed to send request to http://127.0.0.1:37188/exa.language_server_pb.LanguageServerService/GetCompletions, status code: GatewayTimeout
Language Server: E1222 20:25:03.614538  7648 embedding.go:41] GetEmbeddings error: net/http: TLS handshake timeout
Language Server: E1222 20:25:03.614538  7648 embedding.go:41] GetEmbeddings error: net/http: TLS handshake timeout
Language Server: E1222 20:25:03.828937  7648 embedding.go:41] GetEmbeddings error: net/http: TLS handshake timeout
Language Server: E1222 20:25:03.829267  7648 embedding.go:41] GetEmbeddings error: net/http: TLS handshake timeout
Language Server: E1222 20:25:04.055919  7648 embedding.go:41] GetEmbeddings error: net/http: TLS handshake timeout
Language Server: E1222 20:25:35.656753  7648 completions_state_manager.go:833] Error streaming completions: context deadline exceeded
Language Server: E1222 20:25:35.656753  7648 completion.go:215] Completion 1 from source PROVIDER_SOURCE_AUTOCOMPLETE error: context deadline exceeded
Error: Failed to send request to http://127.0.0.1:37188/exa.language_server_pb.LanguageServerService/GetCompletions, status code: GatewayTimeout
```
