### ISSUE TITLE
CodeLens thing keeps appearing randomly

### ISSUE THREAD

**Issue by yuriy-sng** [Exafunction/codeium#46]
Even though i have it set as "false".

I click the X, which takes me to the settings and it shows "false" and then when I return the editor the lens is not there anymore.

Version: 1.87.1 (user setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by ilahazs** [comment]
Same problem

**Comment by ilahazs** [comment]
BUG Appear Randomly :
![BUG CODEIUM](https://github.com/Exafunction/codeium/assets/68785569/e9e3a6bd-e67f-48ea-af54-e34fb4269cef)

Settings User :
![Sunday_17_March_2024_00-51-40](https://github.com/Exafunction/codeium/assets/68785569/2e1ab9e8-2f34-4bce-93ab-96e0e2d294f8)

Settings User [Remote SSH] :
![Sunday_17_March_2024_00-51-51](https://github.com/Exafunction/codeium/assets/68785569/80eebb04-03f9-4fe1-9d06-937d9bc4f7af)

Codeium Version v1.8.10:
![image](https://github.com/Exafunction/codeium/assets/68785569/b592de48-d95c-4177-97ec-5cc713d2a703)

**Comment by pqn** [comment]
This should be resolved in the next release (within the next couple of days)
