### ISSUE TITLE
codeium.enableCodeLens false not disabling code lens properly

### ISSUE THREAD

**Issue by amrthdivakr** [Exafunction/codeium#47]
After v1.8 update, when `codeium.enableCodeLens` set to `false` is not working as expected. It hides code lens at first but after a while it reappears. It also flickers on and off constantly, this shifts the code in the text editor up and down.

**Comment by lwpassvoice** [comment]
same here, in vscode, pre-release version
![image](https://github.com/Exafunction/codeium.vim/assets/22510735/c6d1690c-b3df-436b-9c9f-53a00425ded4)

**Comment by amrthdivakr** [comment]
This is the wrong repo. I realized it after posting the issue.
Try their Discord server's support channel. They're aware of the problem and are working on it.
For now, install a previous version. You'll find it under the uninstall dropdown. I'm using v1.6.39 and it works fine.
![image](https://github.com/Exafunction/codeium.vim/assets/40572846/8293e0df-b058-4d7c-bde0-44815d69b90b)

**Comment by pqn** [comment]
The fix has been merged internally and should be available soon.
