### ISSUE TITLE
Autocompletion stopped working

### ISSUE THREAD

**Issue by Thribs** [Exafunction/codeium#67]
similar to #42

macOs Sonoma 14.5;
vscode-insiders 1.91.0;
Codeium 1.8.22;
language Dart

Tried reinstalling the extension, reloading window, switching to pre-release version. Issue persists for about a week.
Output logs for Codeium empty. Window logs previously showed something along the lines of "cannot register command because command is already registered". Didn't manage to capture it and it's not showing up anymore.

Attempting to run `Codeium: Toggle Autocomplete Enabled for Current Language` shows this error message:
<img width="246" alt="Screenshot 2024-06-11 at 18 13 58" src="https://github.com/Exafunction/codeium/assets/9482597/77afdf6a-6204-4c99-a856-03d0083a5b96">

Side panel is blank:
<img width="270" alt="image" src="https://github.com/Exafunction/codeium/assets/9482597/888fda7a-fc0e-4308-816e-9f81fd30bc91">

**Comment by KrisCarr** [comment]
I get the same error for any command including trying to open the codeium section from the left menu, so the entire thing is totally unusable. On macOS.

Full reinstall of codeium (and VS Code) doesn't fix it, wiping out the `.codeium` and `.vscode-insiders` folders from my home directory. Neither does rolling back the extension to an older version (chose random ones going back over 4 weeks, oldest one I tried was 1.8.36).

In the `Extension Host` Output logs I see this:

```
2024-06-13 12:10:47.671 [error] Activating extension Codeium.codeium failed due to an error:
2024-06-13 12:10:47.671 [error] TypeError: Cannot set property createSecureContext of #<Object> which has only a getter
	at /Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:710222
	at t.initializeCertificateAuthorities (/Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:710359)
	at 11201 (/Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:905018)
	at n (/Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:4105968)
	at /Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:4106718
	at Object.<anonymous> (/Users/kris/.vscode-insiders/extensions/codeium.codeium-1.9.59/dist/extension.js:2:4106749)
	at o._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	.....
```

Looks like something to do with certificate authorities inside Codeium? or setting something the types say it's not allowed to set.

**Comment by KrisCarr** [comment]
Seems happy since today's update for me now.

**Comment by Thribs** [comment]
> Seems happy since today's update for me now.

Indeed. Closing as completed.
Devs, in the future please let us know you're working on a fix

**Comment by fortenforge** [comment]
we didn't do anything 😭

fwiw if you use vscode insiders I think you need to expect a certain amount of instability with both the IDE and the extensions (you get codeium's prerelease extensions automatically on insiders).
