### ISSUE TITLE
Language Server source code for building on Android 

### ISSUE THREAD

**Issue by Haiz14** [Exafunction/codeium#8]
Is it possible to release the language server source code, just to build the binary on Android or some other extreme environments?

Would be really helpful.

**Comment by pqn** [comment]
This is likely too complex for us to extract. What use case do you have in mind? Our Chrome extension uses a remote language server, although the feature set is more limited.

**Comment by Haiz14** [comment]
https://github.com/Exafunction/codeium.vim/issues/8

Since android builds are not supported, i thought of building one myself. Seems not possible then.

**Comment by Haiz14** [comment]
I can write a docker container to build it if it's alright?

**Comment by pqn** [comment]
If you are looking for single-file autocomplete, I would recommend looking at the remote language server usage in the Chrome extension. Otherwise, I don't think we're able to accept external integrations into our build system (like images) right now.

**Comment by Haiz14** [comment]
Closing it then, :(
