### ISSUE TITLE
VSCode autocomplete stop working

### ISSUE THREAD

**Issue by hecgribel** [Exafunction/codeium#98]
After install Codeium 1.22.4 extension for VSCode (I'm using v1.76.2 on Mac OS Sequoia 15.0.1), the autocomplete suggestions while typing have stopped working. Today I updated to 1.22.5, but same issue.

Inline tools of Codeium are working fine: refactor, explain, etc...

Meanwhile I rolled back to 1.16.18, where everything works like a charm.

**Comment by fortenforge** [comment]
You'll need to update your version of VSCode.
